name: Build & Deploy Backend

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASS }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

    - name: Build image
      run: docker build -t keyn1990/backend-pay-flow:latest .

    - name: Push image
      run: docker push keyn1990/backend-pay-flow:latest

    - name: Deploy
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: 192.67.197.185
        username: root
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /root/bankflay
          docker-compose pull
          docker-compose up -d
